apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: 211125558772.dkr.ecr.ca-central-1.amazonaws.com/k-food-app:7
        name: guestbook-ui
        ports:
        - containerPort: 8080
